language: haxe

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.4"

install:
  # We use Sure for sanity checking
  - haxelib install sure
  
  # Get the documentation generator
  - haxelib install dox
  
  # Unit test runner dependencies
  - haxelib install utest

script:
  # Package the haxelib
  - chmod +x ./package_haxelib.sh
  - ./package_haxelib.sh
  
  # Generate documentation
  - pushd dox
  - chmod +x ./generate_docs.sh
  - ./generate_docs.sh
  - popd
  
  # Build/run the unit tests
  - pushd unit
  - haxe tests.hxml -neko bin/neko.n
  - chmod +x ./bin/neko.n
  - neko bin/neko.n
  - popd

# Deploy the built haxelib to GitHub releases
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_API_KEY
  file: MacroTween.zip
  on:
    tags: true

# Deploy generated documentation to GitHub Pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs/
  github_token: $GITHUB_API_KEY
  on:
    branch: master