language: haxe

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.4"

script:
  # Package the haxelib
  - chmod +x ./package_haxelib.sh
  - ./package_haxelib.sh
  
  # TODO generate documentation
  
  # Build/run the unit tests
  - pushd unit
  - haxe test.hxml
  - popd

# Deploy the built haxelib to GitHub releases
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: MacroTween.zip
  skip_cleanup: true
  on:
    tags: true

# Deploy generated documentation to GitHub Pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs/
  github_token: $GITHUB_API_KEY
  on:
    branch: master